-- database/seed_data.sql
-- Initial reference data

INSERT INTO centers (center_id, name, investigator, country, consortium) VALUES
(0, 'Unknown', 'Unkown','Unknown', 'Unknown'),
(1, 'Academic-Medical-Center-Amsterdam', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(2, 'Addenbrookes', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(3, 'Alfred', 'Miles Sparrow', 'Australia', 'ANZIBDC'),
(4, 'Austria', 'Andre Franke', 'Germany', 'Regeneron_Genetics_Center'),
(5, 'Cambridge', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(6, 'CCFA', 'James Lewis', 'United States', 'SPARC'),
(7, 'Cedars-Sinai', 'Dermot McGovern', 'United States', 'NIDDK_IBDGC'),
(8, 'Christchurch', 'Richard Gearry', 'Australia', 'ANZIBDC'),
(9, 'Cleveland Clinic', 'Jean-Paul Achkar', 'United States', ''),
(10, 'Dundee', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(11, 'Edinburgh', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(12, 'Emory', 'Subra Kugathasan', 'United States', 'RISK'),
(13, 'EOIBD', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(14, 'Erasme Hospital ULB', 'Denis Franchimont', 'Belgium', 'Belgium_IBD'),
(15, 'Erasmus-Medical-Center-Rotterdam', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(16, 'Exeter', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(17, 'FMC', 'Bampton', 'Australia', 'ANZIBDC'),
(18, 'Free-University-Medical-Center-Amsterdam', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(19, 'Fremantle', 'Ian Lawrance', 'Australia', 'ANZIBDC'),
(20, 'Hong Kong', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(21, 'IIS Biodonostia', 'Koldo Garcia', 'Spain', 'Basque_IBD'),
(22, 'Italy', 'Anna Latiano', 'Italy', 'Italian_GSA'),
(23, 'Johns Hopkins', 'Steve Brant', 'United States', 'NIDDK_IBDGC'),
(24, 'KIELBC', 'Andre Franke', 'Germany', 'Regeneron_Genetics_Center'),
(25, 'KIELEZE', 'Andre Franke', 'Germany', 'Regeneron_Genetics_Center'),
(26, 'KIELFOC', 'Andre Franke', 'Germany', 'Regeneron_Genetics_Center'),
(27, 'KIELHLITM', 'Andre Franke', 'Germany', 'Regeneron_Genetics_Center'),
(28, 'KIELIBD', 'Andre Franke', 'Germany', 'Regeneron_Genetics_Center'),
(29, 'Leiden-University-Medical-Center', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(30, 'Liege University Hospital', 'Edouard Louis', 'Belgium', 'Belgium_IBD'),
(31, 'LifeLines-DEEP-Cohort', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(32, 'Lithuanian University of Health Sciences', 'Limas Kupcinskas', 'Lithuania', 'Lithuanian_IBD_cohort'),
(33, 'Liverpool', 'Susan O''Connor', 'Australia', 'ANZIBDC'),
(34, 'London', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(35, 'Maastricht-University-Medical-Center', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(36, 'Manchester', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(37, 'Massachusetts General Hospital', 'Ramnik Xavier', 'United States', 'MGH_PRISM'),
(38, 'Mater', 'Jacob Begun', 'Australia', 'ANZIBDC'),
(39, 'MF-UM-CHMGF', 'Uroš Potočnik', 'Slovenia', 'Slovenia'),
(40, 'Montreal', 'John Rioux', 'Canada', 'IGENOMED'),
(41, 'MSCCR', 'Bruce Sands', 'United States', 'MSCCR'),
(42, 'MSSM', 'Judy Cho', 'United States', 'NIDDK_IBDGC'),
(43, 'Newcastle', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(44, 'Norwich', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(45, 'Nottingham', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(46, 'NSHAP', 'Phil Schumm', 'United States', ''),
(47, 'Oxford', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(48, 'Oxford-new', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(49, 'Pittsburgh', 'Richard Duerr', 'United States', 'NIDDK_IBDGC'),
(50, 'Radboud-University-Medical-Center-Nijmegen', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(51, 'RAH', 'Jane Andrews', 'Australia', 'ANZIBDC'),
(52, 'RBWH', 'Graham Radford-Smith', 'Australia', 'ANZIBDC'),
(53, 'Sheffield', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(54, 'SIBDCS', 'Andre Franke', 'Germany', 'Regeneron_Genetics_Center'),
(55, 'Spain', 'Antonio Julià', 'Spain', 'IMIDC_Spain'),
(56, 'St Marks', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(57, 'SVHS', 'Simon Ghaly', 'Australia', 'ANZIBDC'),
(58, 'Sweden-ERS', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(59, 'Sweden-KSH', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(60, 'Sweden-KSS', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(61, 'Sweden-LIU', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(62, 'Sweden-SAS', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(63, 'Sweden-SUL', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(64, 'Sweden-SUM', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(65, 'Sweden-SUO', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(66, 'Sweden-SUS', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(67, 'Sweden-UAS', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(68, 'Sweden-USO', 'Jonas Halfvarson', 'Sweden', 'Sweden_IBD'),
(69, 'TOPPIC', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(70, 'Torbay', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(71, 'Toronto', 'Mark Silverberg', 'Canada', 'NIDDK_IBDGC'),
(72, 'Townsville', 'Gillian Mahy', 'Australia', 'ANZIBDC'),
(73, 'UK', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(74, 'University Hospital Leuven', 'Severine Vermeire', 'Belgium', 'Belgium_IBD'),
(75, 'University of Chicago', 'Judy Cho', 'United States', 'NIDDK_IBDGC'),
(76, 'University of Helsinki', 'Martti Farkkila', 'Finland', 'Finnish_Collections'),
(77, 'University of Miami', 'Jacob McCauley', 'United States', 'NIDDK_IBDGC'),
(78, 'University-Medical-Center-Groningen', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(79, 'University-Medical-Center-Utrecht', 'Rinse Weersma', 'Netherlands', 'Netherlands_UMCG_PSI'),
(80, 'Wellcome Trust', 'Carl Anderson', 'United Kingdom', 'Sanger_Working_Group'),
(81, 'Yale', 'Judy Cho', 'United States', 'NIDDK_IBDGC')
ON CONFLICT (center_id) DO NOTHING;
