FROM python:3.11-slim

WORKDIR /app

RUN mkdir -p /app/htmlcov /app/test-reports

COPY requirements.txt .
COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

COPY . .

CMD ["pytest"]
