---
name: Code Coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test containers
        run: |
          docker-compose -f docker-compose.test.yml build
      - name: Run tests with coverage
        run: |
          docker-compose -f docker-compose.test.yml run --rm test-gsid pytest --cov=. --cov-report=xml --cov-report=html
          docker-compose -f docker-compose.test.yml run --rm test-redcap pytest --cov=. --cov-report=xml --cov-report=html
          docker-compose -f docker-compose.test.yml run --rm test-validator pytest --cov=. --cov-report=xml --cov-report=html
          docker-compose -f docker-compose.test.yml run --rm test-loader pytest --cov=. --cov-report=xml --cov-report=html
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: |
            gsid-service/coverage.xml
            redcap-pipeline/coverage.xml
            fragment-validator/coverage.xml
            table-loader/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            gsid-service/htmlcov/
            redcap-pipeline/htmlcov/
            fragment-validator/htmlcov/
            table-loader/htmlcov/
          retention-days: 30
