---
name: Tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  test-gsid-service:
    name: Test GSID Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create output directories
        run: |
          mkdir -p gsid-service/htmlcov
          mkdir -p gsid-service/test-reports
      - name: Build test container
        run: |
          docker-compose -f docker-compose.test.yml build test-gsid
      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run --rm test-gsid
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gsid-coverage-report
          path: gsid-service/htmlcov/
          retention-days: 30
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gsid-test-report
          path: gsid-service/test-reports/
          retention-days: 30
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: gsid-service/coverage.xml
          flags: gsid-service
          name: gsid-service-coverage
  test-redcap-pipeline:
    name: Test REDCap Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create output directories
        run: |
          mkdir -p redcap-pipeline/htmlcov
          mkdir -p redcap-pipeline/test-reports
      - name: Build test container
        run: |
          docker-compose -f docker-compose.test.yml build test-redcap
      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run --rm test-redcap
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: redcap-coverage-report
          path: redcap-pipeline/htmlcov/
          retention-days: 30
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: redcap-test-report
          path: redcap-pipeline/test-reports/
          retention-days: 30
  test-fragment-validator:
    name: Test Fragment Validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create output directories
        run: |
          mkdir -p fragment-validator/htmlcov
          mkdir -p fragment-validator/test-reports
      - name: Build test container
        run: |
          docker-compose -f docker-compose.test.yml build test-validator
      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run --rm test-validator
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validator-coverage-report
          path: fragment-validator/htmlcov/
          retention-days: 30
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validator-test-report
          path: fragment-validator/test-reports/
          retention-days: 30
  test-table-loader:
    name: Test Table Loader
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create output directories
        run: |
          mkdir -p table-loader/htmlcov
          mkdir -p table-loader/test-reports
      - name: Build test container
        run: |
          docker-compose -f docker-compose.test.yml build test-loader
      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml run --rm test-loader
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: loader-coverage-report
          path: table-loader/htmlcov/
          retention-days: 30
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: loader-test-report
          path: table-loader/test-reports/
          retention-days: 30
